development: &default
  adapter: postgresql
  database: <%= ENV.fetch('MODULOTECH-TEST-RAILS_DATABASE_NAME', 'modulotech-test-rails') %>
  username: <%= ENV.fetch('MODULOTECH-TEST-RAILS_DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('MODULOTECH-TEST-RAILS_DATABASE_PASSWORD', 'postgres') %>
  #HOST FOR DOCKER
  host: host.docker.internal
  #HOST FOR LOCAL
  #host: localhost 
  #host: <%= ENV.fetch('MODULOTECH-TEST-RAILS_DATABASE_HOST', 'postgres') %>
  port: <%= ENV.fetch('MODULOTECH-TEST-RAILS_DATABASE_PORT', 5432) %>

test:
  <<: *default
  database: <%= ENV.fetch('MODULOTECH-TEST-RAILS_TEST_DATABASE_NAME', 'modulotech-test-rails_test') %>

staging:
  <<: *default

production:
  <<: *default
